### ISSUE TITLE
Add images

### ISSUE THREAD

**Issue by sastrakhan** [CodeForBaltimore/civicideahubV2#6]
1. Create images directory 
2. Populate with test images
3. Add mock image URLs to mock data (mock-data/projects.json)
4. Ensure the mock data image urls work with images

**Comment by AustinHudson** [comment]
Hi Sean, I'm looking to get some more practice contributing to open source projects. Do you mind if I take this issue?

**Comment by sastrakhan** [comment]
Go for it!  Thanks Austin.

**Comment by sastrakhan** [comment]
I just saw the images @AustinHudson.  They look great!  Thanks.
